package classes;

public enum EditMenuItems {
    UNDO, REDO, CUT, COPY, PASTE, FLIP_HORIZONTALLY,
    FLIP_VERTICALLY, ROTATE_RIGHT90, ROTATE_RIGHT180,
    ROTATE_LEFT90, EDIT, ROTATE, FLIP, DELETE, DESELECT, ROTATE_LEFT180
}
